version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: library_postgres-db
    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: library_user
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

networks:
  default:
    driver: bridge
